### ISSUE TITLE
No es conserven les majúscules quan s'eliminen els diacrítics antics

### ISSUE THREAD

**Issue by jaumeortola** [apertium/apertium-cat#6]
`$ echo "Soy yo" | apertium -d . spa-cat`
`Sóc jo`
`$ echo "Soy yo" | apertium -d . spa-cat_iec2017`
`soc jo`

No es pot resoldre afegint una altra entrada per a les majúscules. Com es podria arreglar?

**Comment by xavivars** [comment]
@ftyers alguna idea de què pot estar passant? Els diacrítics es gestionen amb un nou mode "intergeneration", però és una còpia pràcticament igual al postgeneration.... I el que és pitjor, tant per a llevar els diacrítics com per a posar-los s'utilitza el mateix mode, per a llevar sempre la marca encara que no hi haja transformació...

**Comment by xavivars** [comment]
Ok, turns out that the reason why it works in the first case is because of a _bug_

https://github.com/apertium/lttoolbox/blob/master/lttoolbox/fst_processor.cc#L2194

`$ echo "Soy yo" | apertium -d . spa-cat-dgen | ./lt-proc -x /tmp/vells.bin
Target: /Sóc First: 0 - All: 0
Target[i] c - Target[i-1] ó
Sóc jo`

`$ echo "Soy yo" | apertium -d . spa-cat-dgen | ./lt-proc -x /tmp/vells.bin
Target: /Sóc First: 0 - All: 0
Target[i] c - Target[i-1] ó
Sóc jo`

It's not replacing the uppercase into a lowercase just because it finds "ó" to be non-alphabetic, and then it doesn't convert the `S` into lowercase.

I almost copy-pasted the intergeneration code from the postgeneration code, but it seems the whole upper/lower case logic is not working properly...

I'll give some thought, but I may remove all that code, and see what happens.

**Comment by xavivars** [comment]
@jaumeortola he eliminat tot el codi que gestiona majúscules/minúscules en el mode, i crec que ara hauria de funcionar bé.... Si vols executar el corpus de proves podem mirar els resultats.
